apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: myapp
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: myapp
    spec:
      containers:
        - name: postgres
          image: postgres:9.6
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: airflow
            - name: POSTGRES_PASSWORD
              value: airflow
            - name: POSTGRES_DB
              value: airflow