apiVersion: v1
kind: Service
metadata:
  name: puckel-service
  labels:
    name: puckel-service
    app: myapp
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: puckel-pod
    app: myapp